-- Phase 11: Final QA, real-user performance monitoring, and release hardening.
-- Safe to run more than once.

create table if not exists public.quality_runs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  release text not null,
  status text not null check (status in ('pass', 'warn', 'fail')),
  score integer not null check (score between 0 and 100),
  summary text not null,
  checks jsonb not null default '[]'::jsonb,
  metrics jsonb not null default '[]'::jsonb,
  total_duration_ms integer not null default 0 check (total_duration_ms >= 0),
  created_at timestamptz not null default now()
);

create index if not exists quality_runs_owner_created_idx
  on public.quality_runs (owner_id, created_at desc);

alter table public.quality_runs enable row level security;

drop policy if exists "quality_runs_select_own" on public.quality_runs;
create policy "quality_runs_select_own"
  on public.quality_runs for select
  to authenticated
  using (owner_id = auth.uid());

drop policy if exists "quality_runs_insert_own" on public.quality_runs;
create policy "quality_runs_insert_own"
  on public.quality_runs for insert
  to authenticated
  with check (owner_id = auth.uid());

drop policy if exists "quality_runs_delete_own" on public.quality_runs;
create policy "quality_runs_delete_own"
  on public.quality_runs for delete
  to authenticated
  using (owner_id = auth.uid());

create table if not exists public.quality_web_vitals (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  metric_id text not null,
  name text not null check (name in ('CLS', 'FCP', 'INP', 'LCP', 'TTFB')),
  value double precision not null check (value >= 0),
  delta double precision not null default 0,
  rating text not null check (rating in ('good', 'needs-improvement', 'poor')),
  navigation_type text,
  path text,
  user_agent text,
  created_at timestamptz not null default now(),
  unique (owner_id, metric_id)
);

create index if not exists quality_web_vitals_owner_created_idx
  on public.quality_web_vitals (owner_id, created_at desc);
create index if not exists quality_web_vitals_owner_name_created_idx
  on public.quality_web_vitals (owner_id, name, created_at desc);

alter table public.quality_web_vitals enable row level security;

drop policy if exists "quality_web_vitals_select_own" on public.quality_web_vitals;
create policy "quality_web_vitals_select_own"
  on public.quality_web_vitals for select
  to authenticated
  using (owner_id = auth.uid());

drop policy if exists "quality_web_vitals_insert_own" on public.quality_web_vitals;
create policy "quality_web_vitals_insert_own"
  on public.quality_web_vitals for insert
  to authenticated
  with check (owner_id = auth.uid());

drop policy if exists "quality_web_vitals_update_own" on public.quality_web_vitals;
create policy "quality_web_vitals_update_own"
  on public.quality_web_vitals for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists "quality_web_vitals_delete_own" on public.quality_web_vitals;
create policy "quality_web_vitals_delete_own"
  on public.quality_web_vitals for delete
  to authenticated
  using (owner_id = auth.uid());

comment on table public.quality_runs is
  'Owner-scoped Phase 11 automated quality-assurance run history.';
comment on table public.quality_web_vitals is
  'Owner-scoped real-user Web Vitals captured from authenticated dashboard sessions.';
