-- Phase 8: Production readiness, private error reporting, and release diagnostics.
-- Run after database/phase7_workspace_finalization.sql.

begin;

create table if not exists public.system_error_logs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  source text not null default 'application',
  message text not null,
  digest text null,
  stack text null,
  path text null,
  request_id text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint system_error_logs_source_length check (char_length(source) between 1 and 80),
  constraint system_error_logs_message_length check (char_length(message) between 1 and 2000),
  constraint system_error_logs_digest_length check (digest is null or char_length(digest) <= 160),
  constraint system_error_logs_path_length check (path is null or char_length(path) <= 1000),
  constraint system_error_logs_request_length check (request_id is null or char_length(request_id) <= 160)
);

create index if not exists idx_system_error_logs_owner_created
  on public.system_error_logs(owner_id, created_at desc);

alter table public.system_error_logs enable row level security;
revoke all on public.system_error_logs from anon;
grant select, insert, delete on public.system_error_logs to authenticated;
grant usage, select on sequence public.system_error_logs_id_seq to authenticated;

drop policy if exists phase8_error_logs_owner_select on public.system_error_logs;
drop policy if exists phase8_error_logs_owner_insert on public.system_error_logs;
drop policy if exists phase8_error_logs_owner_delete on public.system_error_logs;

create policy phase8_error_logs_owner_select
  on public.system_error_logs for select to authenticated
  using (owner_id = auth.uid());

create policy phase8_error_logs_owner_insert
  on public.system_error_logs for insert to authenticated
  with check (owner_id = auth.uid());

create policy phase8_error_logs_owner_delete
  on public.system_error_logs for delete to authenticated
  using (owner_id = auth.uid());

create or replace function public.purge_own_system_error_logs(p_days integer default 90)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  deleted_count bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  if p_days < 7 or p_days > 3650 then
    raise exception 'Retention days must be between 7 and 3650';
  end if;

  delete from public.system_error_logs
  where owner_id = auth.uid()
    and created_at < now() - make_interval(days => p_days);
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

grant execute on function public.purge_own_system_error_logs(integer) to authenticated;
revoke execute on function public.purge_own_system_error_logs(integer) from anon;

commit;

select 'phase8_system_error_logs' as check_name, count(*)::bigint as result
from public.system_error_logs;
