-- Phase 9: Production deployment, cutover tracking, smoke tests, and rollback history.
-- Run after database/phase8_production_readiness.sql.

begin;

create extension if not exists pgcrypto;

create table if not exists public.deployment_releases (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  release_tag text not null,
  environment text not null default 'production',
  status text not null default 'draft',
  deployment_url text null,
  commit_sha text null,
  notes text null,
  started_at timestamptz null,
  deployed_at timestamptz null,
  completed_at timestamptz null,
  rolled_back_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint deployment_releases_tag_length check (char_length(release_tag) between 1 and 80),
  constraint deployment_releases_environment check (environment in ('preview', 'production')),
  constraint deployment_releases_status check (status in ('draft', 'ready', 'deploying', 'live', 'failed', 'rolled_back')),
  constraint deployment_releases_url_length check (deployment_url is null or char_length(deployment_url) <= 1000),
  constraint deployment_releases_commit_length check (commit_sha is null or char_length(commit_sha) <= 120),
  constraint deployment_releases_notes_length check (notes is null or char_length(notes) <= 5000)
);

create unique index if not exists idx_deployment_releases_owner_tag
  on public.deployment_releases(owner_id, release_tag);
create index if not exists idx_deployment_releases_owner_created
  on public.deployment_releases(owner_id, created_at desc);

create table if not exists public.deployment_smoke_tests (
  id bigint generated by default as identity primary key,
  release_id uuid not null references public.deployment_releases(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  test_key text not null,
  category text not null,
  label text not null,
  required boolean not null default true,
  status text not null default 'not_run',
  detail text null,
  checked_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint deployment_smoke_tests_key_length check (char_length(test_key) between 1 and 100),
  constraint deployment_smoke_tests_category_length check (char_length(category) between 1 and 80),
  constraint deployment_smoke_tests_label_length check (char_length(label) between 1 and 240),
  constraint deployment_smoke_tests_status check (status in ('not_run', 'pass', 'fail', 'skipped')),
  constraint deployment_smoke_tests_detail_length check (detail is null or char_length(detail) <= 5000),
  constraint deployment_smoke_tests_release_key unique (release_id, test_key)
);

create index if not exists idx_deployment_smoke_tests_release
  on public.deployment_smoke_tests(release_id, category, id);
create index if not exists idx_deployment_smoke_tests_owner
  on public.deployment_smoke_tests(owner_id, updated_at desc);

create table if not exists public.deployment_events (
  id bigint generated by default as identity primary key,
  release_id uuid not null references public.deployment_releases(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint deployment_events_type_length check (char_length(event_type) between 1 and 80),
  constraint deployment_events_message_length check (char_length(message) between 1 and 2000)
);

create index if not exists idx_deployment_events_release_created
  on public.deployment_events(release_id, created_at desc);
create index if not exists idx_deployment_events_owner_created
  on public.deployment_events(owner_id, created_at desc);

create or replace function public.phase9_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists phase9_deployment_releases_updated_at on public.deployment_releases;
create trigger phase9_deployment_releases_updated_at
before update on public.deployment_releases
for each row execute function public.phase9_set_updated_at();

drop trigger if exists phase9_deployment_smoke_tests_updated_at on public.deployment_smoke_tests;
create trigger phase9_deployment_smoke_tests_updated_at
before update on public.deployment_smoke_tests
for each row execute function public.phase9_set_updated_at();

alter table public.deployment_releases enable row level security;
alter table public.deployment_smoke_tests enable row level security;
alter table public.deployment_events enable row level security;

revoke all on public.deployment_releases from anon;
revoke all on public.deployment_smoke_tests from anon;
revoke all on public.deployment_events from anon;

grant select, insert, update, delete on public.deployment_releases to authenticated;
grant select, insert, update, delete on public.deployment_smoke_tests to authenticated;
grant select, insert on public.deployment_events to authenticated;
grant usage, select on sequence public.deployment_smoke_tests_id_seq to authenticated;
grant usage, select on sequence public.deployment_events_id_seq to authenticated;

drop policy if exists phase9_releases_owner_select on public.deployment_releases;
drop policy if exists phase9_releases_owner_insert on public.deployment_releases;
drop policy if exists phase9_releases_owner_update on public.deployment_releases;
drop policy if exists phase9_releases_owner_delete on public.deployment_releases;

create policy phase9_releases_owner_select
  on public.deployment_releases for select to authenticated
  using (owner_id = auth.uid());

create policy phase9_releases_owner_insert
  on public.deployment_releases for insert to authenticated
  with check (owner_id = auth.uid());

create policy phase9_releases_owner_update
  on public.deployment_releases for update to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

create policy phase9_releases_owner_delete
  on public.deployment_releases for delete to authenticated
  using (owner_id = auth.uid());

drop policy if exists phase9_smoke_tests_owner_select on public.deployment_smoke_tests;
drop policy if exists phase9_smoke_tests_owner_insert on public.deployment_smoke_tests;
drop policy if exists phase9_smoke_tests_owner_update on public.deployment_smoke_tests;
drop policy if exists phase9_smoke_tests_owner_delete on public.deployment_smoke_tests;

create policy phase9_smoke_tests_owner_select
  on public.deployment_smoke_tests for select to authenticated
  using (owner_id = auth.uid());

create policy phase9_smoke_tests_owner_insert
  on public.deployment_smoke_tests for insert to authenticated
  with check (
    owner_id = auth.uid()
    and exists (
      select 1 from public.deployment_releases r
      where r.id = release_id and r.owner_id = auth.uid()
    )
  );

create policy phase9_smoke_tests_owner_update
  on public.deployment_smoke_tests for update to authenticated
  using (owner_id = auth.uid())
  with check (
    owner_id = auth.uid()
    and exists (
      select 1 from public.deployment_releases r
      where r.id = release_id and r.owner_id = auth.uid()
    )
  );

create policy phase9_smoke_tests_owner_delete
  on public.deployment_smoke_tests for delete to authenticated
  using (owner_id = auth.uid());

drop policy if exists phase9_events_owner_select on public.deployment_events;
drop policy if exists phase9_events_owner_insert on public.deployment_events;

create policy phase9_events_owner_select
  on public.deployment_events for select to authenticated
  using (owner_id = auth.uid());

create policy phase9_events_owner_insert
  on public.deployment_events for insert to authenticated
  with check (
    owner_id = auth.uid()
    and exists (
      select 1 from public.deployment_releases r
      where r.id = release_id and r.owner_id = auth.uid()
    )
  );

commit;

select 'phase9_deployment_releases' as check_name, count(*)::bigint as result
from public.deployment_releases
union all
select 'phase9_deployment_smoke_tests', count(*)::bigint
from public.deployment_smoke_tests
union all
select 'phase9_deployment_events', count(*)::bigint
from public.deployment_events;
