-- Phase 10: post-launch maintenance, backup verification, daily reports, and API rate limits.
-- Run after database/phase9_production_cutover.sql.

begin;

create extension if not exists pgcrypto;

create table if not exists public.maintenance_runs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  run_type text not null default 'manual',
  status text not null default 'healthy',
  summary text not null,
  report jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint maintenance_runs_type_check check (run_type in ('manual', 'cron', 'cleanup')),
  constraint maintenance_runs_status_check check (status in ('healthy', 'attention', 'critical')),
  constraint maintenance_runs_summary_length check (char_length(summary) between 1 and 2000)
);

create index if not exists idx_maintenance_runs_owner_created
  on public.maintenance_runs(owner_id, created_at desc);

create table if not exists public.backup_verifications (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  filename text not null,
  schema_name text null,
  backup_version integer null,
  status text not null,
  counts jsonb not null default '{}'::jsonb,
  warnings jsonb not null default '[]'::jsonb,
  verified_at timestamptz not null default now(),
  constraint backup_verifications_status_check check (status in ('pass', 'warn', 'fail')),
  constraint backup_verifications_filename_length check (char_length(filename) between 1 and 255),
  constraint backup_verifications_schema_length check (schema_name is null or char_length(schema_name) <= 160)
);

create index if not exists idx_backup_verifications_owner_verified
  on public.backup_verifications(owner_id, verified_at desc);

create table if not exists public.api_rate_limits (
  bucket_key text primary key,
  window_started timestamptz not null default now(),
  request_count integer not null default 0,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now(),
  constraint api_rate_limits_count_check check (request_count >= 0),
  constraint api_rate_limits_key_length check (char_length(bucket_key) between 16 and 160)
);

create index if not exists idx_api_rate_limits_expires
  on public.api_rate_limits(expires_at);

create or replace function public.phase10_consume_rate_limit(
  p_bucket_key text,
  p_limit integer,
  p_window_seconds integer
)
returns table(allowed boolean, remaining integer, reset_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_reset timestamptz;
begin
  if p_bucket_key is null or char_length(p_bucket_key) < 16 then
    raise exception 'Invalid rate-limit key';
  end if;
  if p_limit < 1 or p_limit > 10000 then
    raise exception 'Invalid rate-limit request limit';
  end if;
  if p_window_seconds < 10 or p_window_seconds > 86400 then
    raise exception 'Invalid rate-limit window';
  end if;

  insert into public.api_rate_limits(bucket_key, window_started, request_count, expires_at, updated_at)
  values (
    left(p_bucket_key, 160),
    now(),
    1,
    now() + make_interval(secs => p_window_seconds),
    now()
  )
  on conflict (bucket_key) do update set
    window_started = case
      when public.api_rate_limits.expires_at <= now() then now()
      else public.api_rate_limits.window_started
    end,
    request_count = case
      when public.api_rate_limits.expires_at <= now() then 1
      else public.api_rate_limits.request_count + 1
    end,
    expires_at = case
      when public.api_rate_limits.expires_at <= now()
        then now() + make_interval(secs => p_window_seconds)
      else public.api_rate_limits.expires_at
    end,
    updated_at = now()
  returning request_count, expires_at into v_count, v_reset;

  return query select v_count <= p_limit, greatest(p_limit - v_count, 0), v_reset;
end;
$$;

alter table public.maintenance_runs enable row level security;
alter table public.backup_verifications enable row level security;
alter table public.api_rate_limits enable row level security;

revoke all on public.maintenance_runs from anon;
revoke all on public.backup_verifications from anon;
revoke all on public.api_rate_limits from anon, authenticated;

revoke all on function public.phase10_consume_rate_limit(text, integer, integer) from public;
grant execute on function public.phase10_consume_rate_limit(text, integer, integer) to authenticated, service_role;

grant select, insert, delete on public.maintenance_runs to authenticated;
grant select, insert, delete on public.backup_verifications to authenticated;
grant usage, select on sequence public.backup_verifications_id_seq to authenticated;

drop policy if exists phase10_maintenance_owner_select on public.maintenance_runs;
drop policy if exists phase10_maintenance_owner_insert on public.maintenance_runs;
drop policy if exists phase10_maintenance_owner_delete on public.maintenance_runs;
create policy phase10_maintenance_owner_select on public.maintenance_runs
  for select to authenticated using (owner_id = auth.uid());
create policy phase10_maintenance_owner_insert on public.maintenance_runs
  for insert to authenticated with check (owner_id = auth.uid());
create policy phase10_maintenance_owner_delete on public.maintenance_runs
  for delete to authenticated using (owner_id = auth.uid());

drop policy if exists phase10_backup_owner_select on public.backup_verifications;
drop policy if exists phase10_backup_owner_insert on public.backup_verifications;
drop policy if exists phase10_backup_owner_delete on public.backup_verifications;
create policy phase10_backup_owner_select on public.backup_verifications
  for select to authenticated using (owner_id = auth.uid());
create policy phase10_backup_owner_insert on public.backup_verifications
  for insert to authenticated with check (owner_id = auth.uid());
create policy phase10_backup_owner_delete on public.backup_verifications
  for delete to authenticated using (owner_id = auth.uid());

commit;

select 'phase10_maintenance_runs' as check_name, count(*)::bigint as result
from public.maintenance_runs
union all
select 'phase10_backup_verifications', count(*)::bigint
from public.backup_verifications
union all
select 'phase10_rate_limit_buckets', count(*)::bigint
from public.api_rate_limits;
