-- Damon\'s Archive Phase 12: final acceptance and operational handoff

create table if not exists public.handoff_acceptance_items (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  item_key text not null,
  status text not null default 'pending' check (status in ('pending','pass','fail')),
  evidence text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, item_key)
);

create table if not exists public.handoff_acceptance_runs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  release text not null default 'phase-12-final-handoff',
  status text not null default 'accepted' check (status in ('accepted','reopened')),
  accepted_by text not null,
  notes text,
  readiness jsonb not null default '{}'::jsonb,
  checklist jsonb not null default '[]'::jsonb,
  accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists handoff_items_owner_idx on public.handoff_acceptance_items(owner_id, updated_at desc);
create index if not exists handoff_runs_owner_idx on public.handoff_acceptance_runs(owner_id, accepted_at desc);

alter table public.handoff_acceptance_items enable row level security;
alter table public.handoff_acceptance_runs enable row level security;

drop policy if exists "Owners manage handoff items" on public.handoff_acceptance_items;
create policy "Owners manage handoff items" on public.handoff_acceptance_items
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Owners manage handoff runs" on public.handoff_acceptance_runs;
create policy "Owners manage handoff runs" on public.handoff_acceptance_runs
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

grant select, insert, update, delete on public.handoff_acceptance_items to authenticated;
grant select, insert, update, delete on public.handoff_acceptance_runs to authenticated;
grant usage, select on all sequences in schema public to authenticated;
