"use client";

import { FileText, Loader2, Paperclip, Search, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import type { AssignmentAttachment } from "@/lib/assignments/types";
import { formatBytes } from "@/lib/files/utils";

export function AttachmentManager({ assignmentId, initialAttachments }: { assignmentId: number; initialAttachments: AssignmentAttachment[] }) {
  const router = useRouter();
  const [items, setItems] = useState(initialAttachments);
  const [files, setFiles] = useState<AssignmentAttachment[]>([]);
  const [q, setQ] = useState("");
  const [loading, setLoading] = useState(false);
  const [busyId, setBusyId] = useState<number | null>(null);

  async function findFiles() { setLoading(true); try { const response = await fetch(`/api/assignments/files?q=${encodeURIComponent(q)}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Could not load files."); setFiles(payload.files ?? []); } catch (error) { window.alert(error instanceof Error ? error.message : "Could not load files."); } finally { setLoading(false); } }
  async function link(file: AssignmentAttachment) { setBusyId(file.id); try { const response = await fetch(`/api/assignments/${assignmentId}/files`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileId: file.id }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Could not link file."); setItems((current) => current.some((entry) => entry.id === file.id) ? current : [...current, file]); router.refresh(); } catch (error) { window.alert(error instanceof Error ? error.message : "Could not link file."); } finally { setBusyId(null); } }
  async function unlink(file: AssignmentAttachment) { if (!window.confirm(`Remove “${file.title}” from this assignment?`)) return; setBusyId(file.id); try { const response = await fetch(`/api/assignments/${assignmentId}/files/${file.id}`, { method: "DELETE" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Could not unlink file."); setItems((current) => current.filter((entry) => entry.id !== file.id)); router.refresh(); } catch (error) { window.alert(error instanceof Error ? error.message : "Could not unlink file."); } finally { setBusyId(null); } }

  return <div className="space-y-4"><div className="flex gap-2"><label className="relative flex-1"><Search className="pointer-events-none absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); findFiles(); } }} placeholder="Search Important Files" className="min-h-11 w-full rounded-2xl border border-white/10 pl-10 pr-4 text-sm outline-none focus:border-cyan-300/45 focus:ring-4 focus:ring-cyan-300/15" /></label><button onClick={findFiles} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-white/10 px-4 text-sm font-semibold hover:bg-white/[0.06]">{loading ? <Loader2 className="size-4 animate-spin" /> : <Paperclip className="size-4" />}Find files</button></div>{files.length ? <div className="max-h-52 space-y-2 overflow-auto rounded-2xl border border-white/10 p-2">{files.filter((file) => !items.some((item) => item.id === file.id)).map((file) => <button key={file.id} onClick={() => link(file)} disabled={busyId === file.id} className="flex w-full items-center gap-3 rounded-xl p-2 text-left hover:bg-white/[0.06]"><FileText className="size-5 text-cyan-300" /><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{file.title}</strong><small className="block truncate text-xs text-slate-400">{file.original_filename}</small></span>{busyId === file.id ? <Loader2 className="size-4 animate-spin" /> : <Paperclip className="size-4" />}</button>)}</div> : null}{items.length ? <div className="grid gap-3 sm:grid-cols-2">{items.map((file) => <div key={file.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.045] p-3.5"><Link href={`/dashboard/files/${file.id}`} className="flex min-w-0 flex-1 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-cyan-400/10 text-cyan-300"><FileText className="size-5" /></span><span className="min-w-0"><strong className="block truncate text-sm text-slate-100">{file.title}</strong><small className="block truncate text-xs text-slate-400">{file.original_filename} · {formatBytes(file.file_size)}</small></span></Link><button onClick={() => unlink(file)} className="grid size-9 place-items-center rounded-full text-red-300 hover:bg-red-400/10">{busyId === file.id ? <Loader2 className="size-4 animate-spin" /> : <Trash2 className="size-4" />}</button></div>)}</div> : <p className="rounded-2xl bg-white/[0.035] p-4 text-sm text-slate-400">No linked files yet.</p>}</div>;
}
