"use client";

import { sha256ForDuplicateCheck, uploadResumable } from "@/lib/files/resumable-client";

export async function saveGeneratedFileToArchive(
  file: File,
  options: { folderPath?: string; description?: string; category?: string } = {},
): Promise<{ fileId: number }> {
  const checksumSha256 = await sha256ForDuplicateCheck(file);
  const basePayload = {
    originalName: file.name,
    fileSize: file.size,
    mimeType: file.type || "application/octet-stream",
    folderPath: normalizeFolder(options.folderPath ?? "Tools Output"),
    description: options.description ?? "Generated by Archive Tools",
    category: options.category ?? "Tools Output",
    documentDate: "",
    checksumSha256,
  };

  let response = await fetch("/api/files/upload/prepare", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(basePayload),
  });
  let payload = (await response.json()) as {
    fileId?: number;
    uploadToken?: string;
    objectPath?: string;
    error?: string;
    code?: string;
  };

  if (response.status === 409 && payload.code === "DUPLICATE") {
    response = await fetch("/api/files/upload/prepare", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...basePayload, duplicateStrategy: "keep_both" }),
    });
    payload = (await response.json()) as typeof payload;
  }

  if (!response.ok || !payload.fileId || !payload.uploadToken || !payload.objectPath) {
    throw new Error(payload.error || "Could not prepare the generated file for your archive.");
  }

  try {
    await uploadResumable(file, {
      fileId: payload.fileId,
      uploadToken: payload.uploadToken,
      objectPath: payload.objectPath,
    }, () => undefined);

    const complete = await fetch("/api/files/upload/complete", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ uploadToken: payload.uploadToken }),
    });
    const completePayload = (await complete.json()) as { error?: string; fileId?: number };
    if (!complete.ok) throw new Error(completePayload.error || "Could not finalize the generated file.");
    return { fileId: Number(completePayload.fileId ?? payload.fileId) };
  } catch (error) {
    await fetch("/api/files/upload/cancel", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ uploadToken: payload.uploadToken }),
    }).catch(() => undefined);
    throw error;
  }
}

function normalizeFolder(value: string): string {
  return value
    .replace(/\\/g, "/")
    .split("/")
    .map((part) => part.trim())
    .filter((part) => part && part !== "." && part !== "..")
    .join("/")
    .slice(0, 1000);
}
